export const EVENTS = {
  JOIN_POST: "JOIN_POST",
  LEAVE_POST: "LEAVE_POST",
  LIKE_POST: "LIKE_POST",
  POST_LIKED: "POST_LIKED",
  ADD_COMMENT: "ADD_COMMENT",
  NEW_COMMENT: "NEW_COMMENT",
  DELETE_COMMENT: "DELETE_COMMENT",
  COMMENT_DELETED: "COMMENT_DELETED",
};